# Generated by Django 3.0.6 on 2020-06-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
