# Generated by Django 3.0.6 on 2020-06-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default=' ', max_length=50, null=True)),
            ],
        ),
    ]
